### ISSUE TITLE
Consider adding and releasing module under an appropriate open source license

### ISSUE THREAD

**Issue by joshgillies** [maks/node-matrix-jsapi#1]
Hey there,

I'd like to contribute to this project, however, I am deterred from doing so due to a lack of an appropriate open source license. Currently the only mention of a license comes from the notice Squiz provides as default with their implementation for the JavaScript API (https://github.com/maks/node-matrix-jsapi/blob/master/lib/matrix-api.js#L1-L13), one which likely only applies to Squiz Matrix source code including the Squiz Matrix supplied JavaScript API implementation.

To ensure legal use of and contribution to this project might I suggest adopting an appropriate open source license for this code, and removing any Squiz supplied license that likely doesn't apply to this code.

I'd happily recommend adopting [MIT](http://choosealicense.com/licenses/mit/), however, it's probably best for you to chose something based on your hopes for the project (see: http://choosealicense.com/).

**Comment by joshgillies** [comment]
I can supply a PR to make the appropriate changes if that makes it easier for you?

**Comment by maks** [comment]
@joshgillies Given I have only made modifications to the original file from Matrix CMS to port it to run in Node, I believe its appropriate to retain the GPL v2 license that it was distributed under.
I'll update this repo with that shortly.
Also as you can tell from the commits, I haven't been using or maintaining this module for some time now so I'm fine for you to start your own fork with any changes/fixes you need.

**Comment by maks** [comment]
Fixed in b8028ede9011ef6976f17bb890c9cc4ce3f0567e

**Comment by joshgillies** [comment]
@maks thanks, I'll PR against this repo when I get done with the changes I'm working on.
